import { ListeningSet } from '@/types/listening';

export const MOCK_LISTENING_SETS: ListeningSet[] = [
  {
    id: 'listening-set-1',
    title: 'Riverside Sports & Fitness Club Membership',
    section: 'SECTION_1',
    sectionNumber: 1,
    context: '일상 생활 대화 (전화 문의 및 회원 가입 신청)',
    scenarioDescription:
      '신규 회원이 스포츠 클럽 프런트 데스크 직원과 통화하며 시설 이용 시간, 회원권 종류, 결제 금액 및 개인 정보를 등록하는 대화입니다.',
    wordLimitRule: 'NO MORE THAN TWO WORDS AND/OR A NUMBER',
    dialogue: [
      {
        speaker: 'Receptionist',
        gender: 'female',
        accent: 'en-GB',
        text: 'Good morning, Riverside Fitness and Leisure Club. How can I help you today?',
      },
      {
        speaker: 'Alex',
        gender: 'male',
        accent: 'en-GB',
        text: 'Hello. I’ve just moved to the neighborhood, and I’m interested in joining your sports center. Could you give me some information about the membership plans?',
      },
      {
        speaker: 'Receptionist',
        gender: 'female',
        accent: 'en-GB',
        text: 'Certainly! We have several membership tiers depending on when you plan to visit. Our peak membership covers all hours, while the off-peak plan is valid from 9:00 AM until 4:00 PM on weekdays.',
      },
      {
        speaker: 'Alex',
        gender: 'male',
        accent: 'en-GB',
        text: 'I usually finish work around five in the evening, so peak membership would definitely suit me better. What facilities does that include?',
      },
      {
        speaker: 'Receptionist',
        gender: 'female',
        accent: 'en-GB',
        text: 'With full peak membership, you get unrestricted access to the gym, the heated Olympic pool, and all squash courts. You can also book the sauna without paying any extra charges.',
        evidenceForQuestionId: 1,
        highlightNote: 'Question 1: Sauna access is included free of charge.',
      },
      {
        speaker: 'Alex',
        gender: 'male',
        accent: 'en-GB',
        text: 'That sounds wonderful! I love using the sauna after an intensive workout. And what are your opening hours on the weekend?',
      },
      {
        speaker: 'Receptionist',
        gender: 'female',
        accent: 'en-GB',
        text: 'During weekdays from Monday to Friday, we open early at 6:00 AM and close at 10:00 PM. But on Saturdays and Sundays, the doors open at 7:30 AM and close at 8:00 PM.',
        evidenceForQuestionId: 2,
        highlightNote: 'Question 2: Weekend opening time is 7:30 AM (not 6:00 AM).',
      },
      {
        speaker: 'Alex',
        gender: 'male',
        accent: 'en-GB',
        text: '7:30 AM on weekends is very reasonable. Could you tell me about the monthly fee for peak access?',
      },
      {
        speaker: 'Receptionist',
        gender: 'female',
        accent: 'en-GB',
        text: 'Normally it is sixty pounds per month, but if you sign a 12-month contract today, it reduces to fifty-two pounds per month. However, there is a one-off registration fee of twenty-five pounds.',
        evidenceForQuestionId: 3,
        highlightNote: 'Question 3: Monthly fee on 12-month plan is 52 pounds.',
      },
      {
        speaker: 'Alex',
        gender: 'male',
        accent: 'en-GB',
        text: 'Great, I’ll take the annual contract. Can I register right now over the phone?',
      },
      {
        speaker: 'Receptionist',
        gender: 'female',
        accent: 'en-GB',
        text: 'Of course! Let me take down your details. May I have your full name, please?',
      },
      {
        speaker: 'Alex',
        gender: 'male',
        accent: 'en-GB',
        text: 'Yes, it’s Alex Thompson. That’s T-H-O-M-P-S-O-N.',
      },
      {
        speaker: 'Receptionist',
        gender: 'female',
        accent: 'en-GB',
        text: 'Thank you, Alex. And your home address?',
      },
      {
        speaker: 'Alex',
        gender: 'male',
        accent: 'en-GB',
        text: 'I live at 48 Meadowbrook Lane. That’s M-E-A-D-O-W-B-R-O-O-K Lane.',
        evidenceForQuestionId: 4,
        highlightNote: 'Question 4: Address spelling Meadowbrook.',
      },
      {
        speaker: 'Receptionist',
        gender: 'female',
        accent: 'en-GB',
        text: 'Got it. And what’s the best contact telephone number for you?',
      },
      {
        speaker: 'Alex',
        gender: 'male',
        accent: 'en-GB',
        text: 'My daytime mobile is 07892 415309.',
        evidenceForQuestionId: 5,
        highlightNote: 'Question 5: Telephone number 07892 415309.',
      },
      {
        speaker: 'Receptionist',
        gender: 'female',
        accent: 'en-GB',
        text: '07892 415309. Perfect. Lastly, which day would you like your membership to commence?',
      },
      {
        speaker: 'Alex',
        gender: 'male',
        accent: 'en-GB',
        text: 'Well, today is the 10th of May. Could we start it next Monday, which is the 16th of May?',
        evidenceForQuestionId: 6,
        highlightNote: 'Question 6: Start date is 16th May (not 10th May).',
      },
      {
        speaker: 'Receptionist',
        gender: 'female',
        accent: 'en-GB',
        text: 'The 16th of May is scheduled! Your welcome card and digital key will be ready at the reception desk on your first visit.',
      },
    ],
    questions: [
      {
        id: 1,
        type: 'FORM_COMPLETION',
        prompt: 'Peak membership includes free access to gym, pool, squash courts and the [BLANK]',
        instruction: 'Write NO MORE THAN TWO WORDS for each answer.',
        correctAnswers: ['sauna', 'the sauna'],
        explanation: '직원이 "You can also book the sauna without paying any extra charges"라고 언급하여 무료 이용 시설은 sauna입니다.',
        distractorTrap: '수영장과 스쿼시 코트는 이미 문제에 기재되어 있으므로 추가 혜택인 sauna를 정확히 적어야 합니다.',
        evidenceSentence: 'You can also book the sauna without paying any extra charges.',
      },
      {
        id: 2,
        type: 'FORM_COMPLETION',
        prompt: 'Weekend opening time: [BLANK] AM',
        instruction: 'Write ONE WORD AND/OR A NUMBER for each answer.',
        correctAnswers: ['7:30', '7.30', '7:30 am', '7.30 am'],
        explanation: '평일은 6:00 AM이지만 주말(Saturdays and Sundays)은 7:30 AM에 개장한다고 안내했습니다.',
        distractorTrap: '평일 오픈 시간인 6:00 AM을 먼저 언급하며 혼동을 유도하는 전형적인 IELTS Section 1 함정입니다.',
        evidenceSentence: 'But on Saturdays and Sundays, the doors open at 7:30 AM and close at 8:00 PM.',
      },
      {
        id: 3,
        type: 'FORM_COMPLETION',
        prompt: 'Monthly fee for 12-month contract: £ [BLANK]',
        instruction: 'Write A NUMBER for each answer.',
        correctAnswers: ['52', '52 pounds'],
        explanation: '정가는 60파운드이나, 12개월 계약 시 월 52파운드로 할인된다고 명시했습니다.',
        distractorTrap: '정가 60파운드 및 1회성 가입비 25파운드가 함께 제시되므로 12개월 계약 월회비 52파운드를 골라내야 합니다.',
        evidenceSentence: '...if you sign a 12-month contract today, it reduces to fifty-two pounds per month.',
      },
      {
        id: 4,
        type: 'FORM_COMPLETION',
        prompt: 'Address: 48 [BLANK] Lane',
        instruction: 'Write ONE WORD for each answer.',
        correctAnswers: ['Meadowbrook', 'meadowbrook'],
        explanation: '화자가 "M-E-A-D-O-W-B-R-O-O-K"라고 글자 단위로 스펠링을 불러주었습니다.',
        distractorTrap: '알파벳 스펠링 연음과 철자 실수를 유도하는 문항입니다.',
        evidenceSentence: 'I live at 48 Meadowbrook Lane. That’s M-E-A-D-O-W-B-R-O-O-K Lane.',
      },
      {
        id: 5,
        type: 'FORM_COMPLETION',
        prompt: 'Contact number: [BLANK]',
        instruction: 'Write A NUMBER for each answer.',
        correctAnswers: ['07892 415309', '07892415309'],
        explanation: '화자가 낮 시간 휴대전화 번호로 07892 415309를 전달했습니다.',
        distractorTrap: '숫자 발음 시 "oh" (0)와 끊어 읽는 단위에 유의해야 합니다.',
        evidenceSentence: 'My daytime mobile is 07892 415309.',
      },
      {
        id: 6,
        type: 'FORM_COMPLETION',
        prompt: 'Membership starting date: [BLANK]',
        instruction: 'Write NO MORE THAN TWO WORDS AND/OR A NUMBER.',
        correctAnswers: ['16th May', '16 May', 'May 16th', 'May 16', '16th of May'],
        explanation: '대화 당일은 5월 10일이지만, 실제 회원권 시작일은 다음 주 월요일인 16th of May로 요청했습니다.',
        distractorTrap: '오늘 날짜인 10th of May를 먼저 제시한 뒤 다음 주 월요일인 16th of May로 최종 확정하는 변경 트랩입니다.',
        evidenceSentence: 'Could we start it next Monday, which is the 16th of May?',
      },
    ],
    totalQuestions: 6,
  },
  {
    id: 'listening-set-2',
    title: 'Greenwood Nature Reserve Visitor Guide',
    section: 'SECTION_2',
    sectionNumber: 2,
    context: '사회적 맥락 독백 (자연보호구역 안내 방송)',
    scenarioDescription:
      '공원 관리자가 방문객들에게 신규 생태 트레일 개장, 시설 이용 규칙 및 안전 수칙을 안내하는 설명회 독백입니다.',
    wordLimitRule: 'Choose the correct letter, A, B, or C.',
    dialogue: [
      {
        speaker: 'Park Ranger',
        gender: 'female',
        accent: 'en-AU',
        text: 'Welcome everyone to the Greenwood Nature Reserve orientation talk. My name is Claire, and I am the lead conservation ranger here.',
      },
      {
        speaker: 'Park Ranger',
        gender: 'female',
        accent: 'en-AU',
        text: 'Before you head out to explore our newly expanded pine trails, I want to highlight a few essential updates for this summer season.',
      },
      {
        speaker: 'Park Ranger',
        gender: 'female',
        accent: 'en-AU',
        text: 'First of all, regarding our educational workshops at the Discovery Center: previously we ran these twice every weekend. However, due to popular request from school educators, workshops now operate daily on weekday afternoons as well, starting promptly at 2:00 PM.',
        evidenceForQuestionId: 7,
        highlightNote: 'Question 7: Educational workshops now run on weekday afternoons as well.',
      },
      {
        speaker: 'Park Ranger',
        gender: 'female',
        accent: 'en-AU',
        text: 'Next, a crucial safety regulation about pets: while leashed dogs used to be permitted throughout the park, beginning this month, dogs are strictly prohibited in the northern marsh zone to protect nesting waterfowl. They are only allowed along the paved southern perimeter path.',
        evidenceForQuestionId: 8,
        highlightNote: 'Question 8: Dogs are now banned in the northern marsh zone.',
      },
      {
        speaker: 'Park Ranger',
        gender: 'female',
        accent: 'en-AU',
        text: 'If you’re looking to purchase refreshments, our organic café near the lake entrance is open. Please remember that all single-use plastic bottles have been banned across the entire park since April. Instead, visitors can refill reusable flasks for free at our purified mountain spring water stations situated every 500 meters.',
        evidenceForQuestionId: 9,
        highlightNote: 'Question 9: Plastic bottles are prohibited, but free refill stations are available.',
      },
      {
        speaker: 'Park Ranger',
        gender: 'female',
        accent: 'en-AU',
        text: 'Finally, if you wish to participate in the dusk owl-spotting excursion tonight, tickets must be pre-booked at the visitor desk before 4:30 PM, as we strictly limit each tour group to twelve participants to minimize acoustic disturbance to nocturnal wildlife.',
        evidenceForQuestionId: 10,
        highlightNote: 'Question 10: Owl tour max group size is 12 participants.',
      },
    ],
    questions: [
      {
        id: 7,
        type: 'MULTIPLE_CHOICE',
        prompt: 'When do the Discovery Center workshops currently take place?',
        options: [
          'A. Only twice during the weekend',
          'B. Every morning on weekdays',
          'C. On weekday afternoons as well as weekends',
        ],
        correctAnswers: ['C', 'c', 'On weekday afternoons as well as weekends'],
        explanation: '기존에는 주말 2회였지만, 이번 여름부터 주중 오후 2시(weekday afternoons)에도 매일 진행된다고 설명했습니다.',
        distractorTrap: '과거 기준인 A("previously twice every weekend")를 언급하여 방심한 응시자를 낚는 과거/현재 시제 트랩입니다.',
        evidenceSentence: '...workshops now operate daily on weekday afternoons as well, starting promptly at 2:00 PM.',
      },
      {
        id: 8,
        type: 'MULTIPLE_CHOICE',
        prompt: 'What is the new rule concerning pet dogs in the reserve?',
        options: [
          'A. They are banned completely from the entire park',
          'B. They are forbidden in the northern marsh zone',
          'C. They do not require a leash on the southern path',
        ],
        correctAnswers: ['B', 'b', 'They are forbidden in the northern marsh zone'],
        explanation: '철새 산란지를 보호하기 위해 북쪽 습지 지역(northern marsh zone)에서는 반려견 출입이 전면 금지되었습니다.',
        distractorTrap: '남쪽 도로에서는 여전히 허용되므로 전체 금지(A)는 오답이며, 남쪽에서도 목줄이 필요하므로 C는 오답입니다.',
        evidenceSentence: '...dogs are strictly prohibited in the northern marsh zone to protect nesting waterfowl.',
      },
      {
        id: 9,
        type: 'MULTIPLE_CHOICE',
        prompt: 'What should visitors know about drinking water in the reserve?',
        options: [
          'A. Bottled water must be purchased at the cafe',
          'B. Water can be refilled without cost at stations along the trail',
          'C. There is no drinkable water source outside the visitor center',
        ],
        correctAnswers: ['B', 'b', 'Water can be refilled without cost at stations along the trail'],
        explanation: '일회용 플라스틱 물병은 반입 금지이며, 500미터마다 설치된 정수 스테이션에서 무료(free)로 텀블러를 리필할 수 있습니다.',
        distractorTrap: '카페에서 음료를 살 수 있다는 언급이 있으나 플라스틱 물병은 판매되지 않으며 무료 식수대가 운영됩니다.',
        evidenceSentence: '...visitors can refill reusable flasks for free at our purified mountain spring water stations...',
      },
      {
        id: 10,
        type: 'MULTIPLE_CHOICE',
        prompt: 'Why is the owl-spotting excursion restricted to 12 participants?',
        options: [
          'A. Due to a shortage of safety staff and guides',
          'B. To avoid generating too much noise for night wildlife',
          'C. Because the trail bridge cannot hold heavy crowds',
        ],
        correctAnswers: ['B', 'b', 'To avoid generating too much noise for night wildlife'],
        explanation: '야행성 동물들에게 음향적 방해(acoustic disturbance)를 최소화하기 위해 12명으로 정원을 제한한다고 밝혔습니다.',
        distractorTrap: '어휘 변환(acoustic disturbance = generating too much noise)을 파악해야 정답을 고를 수 있는 문제입니다.',
        evidenceSentence: '...as we strictly limit each tour group to twelve participants to minimize acoustic disturbance to nocturnal wildlife.',
      },
    ],
    totalQuestions: 4,
  },
  {
    id: 'listening-set-3',
    title: 'Renewable Urban Energy Research Presentation',
    section: 'SECTION_3',
    sectionNumber: 3,
    context: '학술 교육 맥락 다자 대화 (지도교수와 두 학생의 과제 튜토리얼)',
    scenarioDescription:
      '환경공학과 학생 리암(Liam)과 클로이(Chloe)가 휴즈 교수(Professor Hughes)와 함께 도심 풍력 발전 과제 발표 준비 상태를 점검하고 피드백을 받는 튜토리얼입니다.',
    wordLimitRule: 'Choose the correct letter, A, B, or C.',
    dialogue: [
      {
        speaker: 'Prof. Hughes',
        gender: 'female',
        accent: 'en-GB',
        text: 'Come in, Liam and Chloe. Take a seat. How are your preparations coming along for next Tuesday’s symposium on micro-wind turbine integration in high-rise buildings?',
      },
      {
        speaker: 'Liam',
        gender: 'male',
        accent: 'en-GB',
        text: 'Thanks Professor. We’ve synthesized most of our case study data from the Rotterdam skyscraper trials, but Chloe and I were disagreeing over which visual graphics to open our presentation with.',
      },
      {
        speaker: 'Chloe',
        gender: 'female',
        accent: 'en-GB',
        text: 'Yes. Liam thought we should begin with complex aerodynamic CFD simulations. But I argued that starting with simple architectural cross-sections would engage the general engineering audience much faster.',
      },
      {
        speaker: 'Prof. Hughes',
        gender: 'female',
        accent: 'en-GB',
        text: 'I definitely side with Chloe here. Remember, your audience consists of urban planners as well as mechanical specialists. If you overload them with mathematical fluid dynamics in the first three minutes, you will lose their attention.',
        evidenceForQuestionId: 11,
        highlightNote: 'Question 11: The professor agrees with Chloe to start with architectural cross-sections.',
      },
      {
        speaker: 'Liam',
        gender: 'male',
        accent: 'en-GB',
        text: 'Fair point. We will move the simulation charts to the appendix then. What about the primary economic drawback we identified?',
      },
      {
        speaker: 'Chloe',
        gender: 'female',
        accent: 'en-GB',
        text: 'We found that while initial installation costs are subsidised by municipal grants, long-term vibration maintenance creates unexpected recurring expenses for building managers.',
        evidenceForQuestionId: 12,
        highlightNote: 'Question 12: Main economic issue is ongoing vibration maintenance costs.',
      },
      {
        speaker: 'Prof. Hughes',
        gender: 'female',
        accent: 'en-GB',
        text: 'That is a critical finding that most commercial vendors gloss over. Make sure to emphasize how resonance dampening dampers can mitigate those expenses.',
      },
      {
        speaker: 'Liam',
        gender: 'male',
        accent: 'en-GB',
        text: 'Will do. Lastly, regarding the concluding section, how should we distribute the remaining speaking time?',
      },
      {
        speaker: 'Prof. Hughes',
        gender: 'female',
        accent: 'en-GB',
        text: 'I suggest Chloe delivers the regulatory policy recommendations, while Liam summarizes the technological innovations. That provides an equitable balance of your individual research domains.',
        evidenceForQuestionId: 13,
        highlightNote: 'Question 13: Chloe handles regulatory policy, Liam covers technology.',
      },
    ],
    questions: [
      {
        id: 11,
        type: 'MULTIPLE_CHOICE',
        prompt: 'Why does Professor Hughes recommend beginning with architectural cross-sections?',
        options: [
          'A. Because the aerodynamic simulations contain calculation errors',
          'B. To avoid overwhelming non-specialist attendees right away',
          'C. Because the event sponsors demanded simpler slides',
        ],
        correctAnswers: ['B', 'b', 'To avoid overwhelming non-specialist attendees right away'],
        explanation: '도시계획가 등 다양한 청중이 있으므로 초반 3분간 복잡한 유체역학 수학 공식으로 청중의 집중을 잃지 않기 위함이라고 조언했습니다.',
        distractorTrap: '시뮬레이션에 오류가 있다는 언급은 없으며(A), 스폰서의 요구도 언급되지 않았습니다(C).',
        evidenceSentence: 'If you overload them with mathematical fluid dynamics in the first three minutes, you will lose their attention.',
      },
      {
        id: 12,
        type: 'MULTIPLE_CHOICE',
        prompt: 'What was the main unexpected economic hurdle identified in the Rotterdam case study?',
        options: [
          'A. High initial purchase prices without government subsidies',
          'B. Premature blade erosion caused by maritime salt fog',
          'C. Recurring expenses required for vibration maintenance',
        ],
        correctAnswers: ['C', 'c', 'Recurring expenses required for vibration maintenance'],
        explanation: '초기 설치비는 보조금으로 충당되지만, 지속적인 진동 유지보수(long-term vibration maintenance) 비용이 예상 밖의 난제라고 밝혔습니다.',
        distractorTrap: '초기 설치비는 보조금(subsidised by municipal grants)이 지원되므로 A는 반대 내용입니다.',
        evidenceSentence: '...long-term vibration maintenance creates unexpected recurring expenses for building managers.',
      },
      {
        id: 13,
        type: 'MULTIPLE_CHOICE',
        prompt: 'How will Liam and Chloe divide the conclusion part of their talk?',
        options: [
          'A. Chloe presents policy guidelines, while Liam focuses on technological features',
          'B. Liam presents all concluding slides to allow Chloe time for Q&A',
          'C. They will present alternating slides together',
        ],
        correctAnswers: ['A', 'a', 'Chloe presents policy guidelines, while Liam focuses on technological features'],
        explanation: '교수가 클로이는 정책 규제 제안(regulatory policy), 리암은 기술 혁신 요약(technological innovations)을 맡도록 추천했습니다.',
        distractorTrap: '누군가 한 명이 다 하거나(B) 번갈아 하는 것(C)이 아닌, 각자의 연구 영역별로 분담하는 방식입니다.',
        evidenceSentence: 'I suggest Chloe delivers the regulatory policy recommendations, while Liam summarizes the technological innovations.',
      },
    ],
    totalQuestions: 3,
  },
  {
    id: 'listening-set-4',
    title: 'The Evolution of Cetacean Echolocation',
    section: 'SECTION_4',
    sectionNumber: 4,
    context: '학술 독백 강의 (해양 생물학 및 생체 음향학 대학 강의)',
    scenarioDescription:
      '해양 생물학 교수가 고래류(이빨고래와 수염고래)의 반향정위(Echolocation) 진화 역사와 해양 소음 공해가 미치는 생태적 영향을 설명하는 심층 학술 강의입니다.',
    wordLimitRule: 'Write ONE WORD ONLY for each answer.',
    dialogue: [
      {
        speaker: 'Lecturer',
        gender: 'male',
        accent: 'en-GB',
        text: 'Good afternoon, colleagues. Today we will explore the evolutionary biomechanics of cetacean echolocation, specifically focusing on the suborder Odontoceti, or toothed whales.',
      },
      {
        speaker: 'Lecturer',
        gender: 'male',
        accent: 'en-GB',
        text: 'Unlike terrestrial mammals that rely predominantly on optical navigation, prehistoric ancestors of modern dolphins adapted to deep marine environments where sunlight penetrates less than two hundred meters.',
      },
      {
        speaker: 'Lecturer',
        gender: 'male',
        accent: 'en-GB',
        text: 'To generate ultrasonic clicks, toothed whales force pressurized air through specialised nasal structures known as phonic lips. The acoustic beams are then focused forward by a bulbous fatty organ located in the forehead called the melon.',
        evidenceForQuestionId: 14,
        highlightNote: 'Question 14: Fatty organ in the forehead is called melon.',
      },
      {
        speaker: 'Lecturer',
        gender: 'male',
        accent: 'en-GB',
        text: 'Upon returning, reflected echoes are not intercepted through external ear canals, which are completely sealed, but rather conducted through the oil-filled cavities inside the lower jaw directly to the middle ear.',
        evidenceForQuestionId: 15,
        highlightNote: 'Question 15: Echoes are received through the lower jaw.',
      },
      {
        speaker: 'Lecturer',
        gender: 'male',
        accent: 'en-GB',
        text: 'Recent bio-logging sensors demonstrate that this biological sonar is so precise that dolphins can detect the exact density and internal organ structure of their prey from distances exceeding seventy meters.',
      },
      {
        speaker: 'Lecturer',
        gender: 'male',
        accent: 'en-GB',
        text: 'However, contemporary shipping traffic and low-frequency military sonar generate chronic acoustic masking. When acoustic noise exceeds safe thresholds, it induces acute disorientation, often leading to catastrophic mass strandings along coastal shorelines.',
        evidenceForQuestionId: 16,
        highlightNote: 'Question 16: Acoustic masking causes disorientation.',
      },
    ],
    questions: [
      {
        id: 14,
        type: 'NOTE_COMPLETION',
        prompt: 'Sound waves are focused forward through a fatty forehead organ termed the [BLANK].',
        instruction: 'Write ONE WORD ONLY for each answer.',
        correctAnswers: ['melon', 'Melon'],
        explanation: '이빨고래의 이마에 위치한 지방 기관으로 초음파를 전방 집속하는 기관은 melon(멜론체)입니다.',
        distractorTrap: '전문 학술 생물학 용어(melon)의 스펠링을 정확히 기재해야 합니다.',
        evidenceSentence: 'The acoustic beams are then focused forward by a bulbous fatty organ located in the forehead called the melon.',
      },
      {
        id: 15,
        type: 'NOTE_COMPLETION',
        prompt: 'Returning acoustic echoes are channelled through oil cavities within the lower [BLANK].',
        instruction: 'Write ONE WORD ONLY for each answer.',
        correctAnswers: ['jaw', 'Jaw'],
        explanation: '반사된 반향음은 귓구멍이 아니라 아래턱(lower jaw) 내부의 지방 공동을 통해 전달됩니다.',
        distractorTrap: '귓구멍(external ear canals)은 막혀있다는 오답 트랩이 제시되므로 lower 뒤에 올 단어인 jaw를 적어야 합니다.',
        evidenceSentence: '...rather conducted through the oil-filled cavities inside the lower jaw directly to the middle ear.',
      },
      {
        id: 16,
        type: 'NOTE_COMPLETION',
        prompt: 'Anthropogenic ocean noise leads to severe [BLANK], resulting in mass beach strandings.',
        instruction: 'Write ONE WORD ONLY for each answer.',
        correctAnswers: ['disorientation', 'Disorientation'],
        explanation: '인간 활동에 의한 소음 공해가 심각한 방향 감각 상실(disorientation)을 유발하여 집단 좌초로 이어진다고 설명했습니다.',
        distractorTrap: '형용사 acute 대신 명사형 disorientation을 정확한 품사로 기입해야 합니다.',
        evidenceSentence: 'When acoustic noise exceeds safe thresholds, it induces acute disorientation...',
      },
    ],
    totalQuestions: 3,
  },
];
